jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v1
    - continue-on-error: true
      name: Set up JDK 17
      uses: actions/setup-java@v1
      with:
        java-version: 17
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew clean test
name: Java CI
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
